FROM ubuntu

RUN apt update && apt install -y python3

RUN apt install -y python3-pip python3-dev default-libmysqlclient-dev build-essential

RUN apt install -y vim

COPY requirements.txt /requirements.txt

RUN pip install -r requirements.txt

RUN django-admin startproject drfapp

WORKDIR /drfapp

RUN cd /drfapp

RUN mv ./drfapp/settings.py ./drfapp/backup-settings.py

RUN mv ./drfapp/urls.py ./drfapp/backup-urls.py

COPY new-settings.py drfapp/settings.py

COPY root-urls.py drfapp/urls.py

EXPOSE 8000/tcp

CMD ["gunicorn","-w 4","-b 0.0.0.0:8000", "--reload","drfapp.wsgi"]